### ISSUE TITLE
clean implementation

### ISSUE THREAD

**Issue by darul75** [gosquared/mmdb-reader#7]
hi,

your implementation is so clean and well documented, a pleasure to read, thanks a lot, and with a cache

great job again, I want to work with you :)

**Comment by jbt** [comment]
Hi @darul75 and sorry for not replying to this issue.

Really great to hear you're appreciating the module. It's comments like yours that're the reason we build stuff like this :)

**Comment by darul75** [comment]
thanks for replying too :)

just a question, how did you manage to play with such a code, playing with metadata part was ok for me, but then to deal with tree, conversion, bit shifting was difficult to debug etc...

do you have some advised about how to debug such a code with NodeJS ? IDE, command line only ?

**Comment by jbt** [comment]
For this module it was mostly a matter of very carefully reading the [MaxMind-DB specification](https://maxmind.github.io/MaxMind-DB/) and building everything out until the tests passed properly.

For debugging anything that didn't work properly, it was mostly a matter of some very un-scientific putting `console.log`s in various places and comparing against the corresponding expected values in [node-maxmind-db](https://github.com/PaddeK/node-maxmind-db) or [MaxMind-DB-Reader-PHP](https://github.com/maxmind/MaxMind-DB-Reader-php)

**Comment by darul75** [comment]
ok, nice thanks a lot, I was reading specification a lot but could not always figure out how to move from one offset to another in data section and with tree walk..

js is good but such code sometimes tricky with only output debug
